Removed batch mode, seems to cause problems when running tests
When running in batch mode (-B) getting error:

shouldNotAllowJmxAccessToUnauthenticatedPrincipals(org.jboss.fuse.vault.karaf.JmxGuardIntegrationTest)  Time elapsed: 6.086 sec  <<< ERROR!
java.rmi.NoSuchObjectException: no such object in table
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)